[package]
name = "clever-isa-emu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

float = [] # X-float
# decimal-fp = ["fp","decimal"]
vector = [] # X-vector

[dependencies]
parking_lot = "0.11.1"
bytemuck = {version="1.7.0",features=["derive","min_const_generics"]}
half = {version="1.7.1",features=["bytemuck"]}
fake-enum = "0.1.2"
lru_time_cache = "0.11.11"
bitflags = "1.2.1"
num-traits = "0.2.14"
rug = "1.13.0"