[package]
name = "clever-isa-emu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fp = []
# decimal-fp = ["fp","decimal"]
simd = [] # TODO, this is not defined by the ISA Spec

[dependencies]
parking_lot = "0.11.1"
bytemuck = {git="https://github.com/Lokathor/bytemuck",features=["derive","min_const_generics"]}

fake-enum = "0.1.2"
lru_time_cache = "0.11.11"
bitflags = "1.2.1"