
[build]
target = "clever-unknown-elf"

[env]
RUST_TARGET_PATH = {value ="targets", relative=true}


[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["panic_immediate_abort"]