[package]
name = "clever-emu-aci"
version = "0.1.0"
edition = "2021"

[dependencies]
aci-registry.workspace = true
aci-firmware-hal.workspace = true
clever-emu-primitives.workspace = true
clever-emu-mem.workspace = true
clever-emu-types.workspace = true
bytemuck.workspace = true